<?php

define('LAST_UPDATE', 'No updates yet... tourney hasn\'t started...');

define('TEAM_POTS', 7);
define('PLAYER_POTS', 2);

# TEAM 1
define('FRANCE_WINS', 0);
define('FRANCE_DRAWS', 0);
define('FRANCE_BNS', 0);
define('GERMANY_WINS', 0);
define('GERMANY_DRAWS', 0);
define('GERMANY_BNS', 0);
define('SPAIN_WINS', 0);
define('SPAIN_DRAWS', 0);
define('SPAIN_BNS', 0);

#TEAM 2
define('ENGLAND_WINS', 0);
define('ENGLAND_DRAWS', 0);
define('ENGLAND_BNS', 0);
define('BELGIUM_WINS', 0);
define('BELGIUM_DRAWS', 0);
define('BELGIUM_BNS', 0);
define('ITALY_WINS', 0);
define('ITALY_DRAWS', 0);
define('ITALY_BNS', 0);
define('PORTUGAL_WINS', 0);
define('PORTUGAL_DRAWS', 0);
define('PORTUGAL_BNS', 0);

#TEAM 3
define('CROATIA_WINS', 0);
define('CROATIA_DRAWS', 0);
define('CROATIA_BNS', 0);
define('AUSTRIA_WINS', 0);
define('AUSTRIA_DRAWS', 0);
define('AUSTRIA_BNS', 0);
define('SWITZERLAND_WINS', 0);
define('SWITZERLAND_DRAWS', 0);
define('SWITZERLAND_BNS', 0);

#TEAM 4
define('WALES_WINS', 0);
define('WALES_DRAWS', 0);
define('WALES_BNS', 0);
define('RUSSIA_WINS', 0);
define('RUSSIA_DRAWS', 0);
define('RUSSIA_BNS', 0);
define('ICELAND_WINS', 0);
define('ICELAND_DRAWS', 0);
define('ICELAND_BNS', 0);
define('POLAND_WINS', 0);
define('POLAND_DRAWS', 0);
define('POLAND_BNS', 0);

#TEAM 5
define('CZECH_WINS', 0);
define('CZECH_DRAWS', 0);
define('CZECH_BNS', 0);
define('SWEDEN_WINS', 0);
define('SWEDEN_DRAWS', 0);
define('SWEDEN_BNS', 0);
define('TURKEY_WINS', 0);
define('TURKEY_DRAWS', 0);
define('TURKEY_BNS', 0);
define('UKRAINE_WINS', 0);
define('UKRAINE_DRAWS', 0);
define('UKRAINE_BNS', 0);

#TEAM 6
define('REPUBLIC_WINS', 0);
define('REPUBLIC_DRAWS', 0);
define('REPUBLIC_BNS', 0);
define('ROMANIA_WINS', 0);
define('ROMANIA_DRAWS', 0);
define('ROMANIA_BNS', 0);
define('SLOVAKIA_WINS', 0);
define('SLOVAKIA_DRAWS', 0);
define('SLOVAKIA_BNS', 0);

#TEAM 7
define('HUNGARY_WINS', 0);
define('HUNGARY_DRAWS', 0);
define('HUNGARY_BNS', 0);
define('NORTHERN_WINS', 0);
define('NORTHERN_DRAWS', 0);
define('NORTHERN_BNS', 0);
define('ALBANIA_WINS', 0);
define('ALBANIA_DRAWS', 0);
define('ALBANIA_BNS', 0);

#PLAYER 1
define('DAVE_GOALS', 0);
define('DAVE_BNS', 0);
define('JOHN_GOALS', 0);
define('JOHN_BNS', 0);
define('BILL_GOALS', 0);
define('BILL_BNS', 0);

#PLAYER 2
define('JEFF_GOALS', 0);
define('JEFF_BNS', 0);
define('MARK_GOALS', 0);
define('MARK_BNS', 0);
define('GREG_GOALS', 0);
define('GREG_BNS', 0);

/*
#PLAYER 3
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 4
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 5
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 6
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 7
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 8
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

#PLAYER 9
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);
define('_GOALS', 0);
define('_BNS', 0);

*/

define('FRANCE', serialize(array(FRANCE_WINS, FRANCE_DRAWS, FRANCE_BNS)));
define('GERMANY', serialize(array(GERMANY_WINS, GERMANY_DRAWS, GERMANY_BNS)));
define('SPAIN', serialize(array(SPAIN_WINS, SPAIN_DRAWS, SPAIN_BNS)));
define('ENGLAND', serialize(array(ENGLAND_WINS, ENGLAND_DRAWS, ENGLAND_BNS)));
define('BELGIUM', serialize(array(BELGIUM_WINS, BELGIUM_DRAWS, BELGIUM_BNS)));
define('ITALY', serialize(array(ITALY_WINS, ITALY_DRAWS, ITALY_BNS)));
define('PORTUGAL', serialize(array(PORTUGAL_WINS, PORTUGAL_DRAWS, PORTUGAL_BNS)));
define('CROATIA', serialize(array(CROATIA_WINS, CROATIA_DRAWS, CROATIA_BNS)));
define('AUSTRIA', serialize(array(AUSTRIA_WINS, AUSTRIA_DRAWS, AUSTRIA_BNS)));
define('SWITZERLAND', serialize(array(SWITZERLAND_WINS, SWITZERLAND_DRAWS, SWITZERLAND_BNS)));
define('WALES', serialize(array(WALES_WINS, WALES_DRAWS, WALES_BNS)));
define('ICELAND', serialize(array(ICELAND_WINS, ICELAND_DRAWS, ICELAND_BNS)));
define('RUSSIA', serialize(array(RUSSIA_WINS, RUSSIA_DRAWS, RUSSIA_BNS)));
define('POLAND', serialize(array(POLAND_WINS, POLAND_DRAWS, POLAND_BNS)));
define('CZECH', serialize(array(CZECH_WINS, CZECH_DRAWS, CZECH_BNS)));
define('SWEDEN', serialize(array(SWEDEN_WINS, SWEDEN_DRAWS, SWEDEN_BNS)));
define('TURKEY', serialize(array(TURKEY_WINS, TURKEY_DRAWS, TURKEY_BNS)));
define('UKRAINE', serialize(array(UKRAINE_WINS, UKRAINE_DRAWS, UKRAINE_BNS)));
define('REPUBLIC', serialize(array(REPUBLIC_WINS, REPUBLIC_DRAWS, REPUBLIC_BNS)));
define('ROMANIA', serialize(array(ROMANIA_WINS, ROMANIA_DRAWS, ROMANIA_BNS)));
define('SLOVAKIA', serialize(array(SLOVAKIA_WINS, SLOVAKIA_DRAWS, SLOVAKIA_BNS)));
define('HUNGARY', serialize(array(HUNGARY_WINS, HUNGARY_DRAWS, HUNGARY_BNS)));
define('NORTHERN', serialize(array(NORTHERN_WINS, NORTHERN_DRAWS, NORTHERN_BNS)));
define('ALBANIA', serialize(array(ALBANIA_WINS, ALBANIA_DRAWS, ALBANIA_BNS)));


define('DAVE', serialize(array(DAVE_GOALS, DAVE_BNS)));
define('JOHN', serialize(array(JOHN_GOALS, JOHN_BNS)));
define('BILL', serialize(array(BILL_GOALS, BILL_BNS)));
define('JEFF', serialize(array(JEFF_GOALS, JEFF_BNS)));
define('MARK', serialize(array(MARK_GOALS, MARK_BNS)));
define('GREG', serialize(array(GREG_GOALS, GREG_BNS)));

