<?php

define('LAST_UPDATE', 'No updates yet... tourney hasn\'t started...');

define('TEAM_POTS', 7);
define('PLAYER_POTS', 2);

define('NORTHERN_FORMATTED', 'N IRELAND');
define('REPUBLIC_FORMATTED', 'REP IRELAND');
define('CZECH_FORMATTED', 'CZECH REP');
define('BRUYNE_FORMATTED', 'DE BRUYNE');

# TEAM 1
define('FRANCE_WINS', 0);
define('FRANCE_DRAWS', 0);
define('FRANCE_BNS', 0);
define('GERMANY_WINS', 0);
define('GERMANY_DRAWS', 0);
define('GERMANY_BNS', 0);
define('SPAIN_WINS', 0);
define('SPAIN_DRAWS', 0);
define('SPAIN_BNS', 0);

#TEAM 2
define('ENGLAND_WINS', 0);
define('ENGLAND_DRAWS', 0);
define('ENGLAND_BNS', 0);
define('BELGIUM_WINS', 0);
define('BELGIUM_DRAWS', 0);
define('BELGIUM_BNS', 0);
define('ITALY_WINS', 0);
define('ITALY_DRAWS', 0);
define('ITALY_BNS', 0);
define('PORTUGAL_WINS', 0);
define('PORTUGAL_DRAWS', 0);
define('PORTUGAL_BNS', 0);

#TEAM 3
define('CROATIA_WINS', 0);
define('CROATIA_DRAWS', 0);
define('CROATIA_BNS', 0);
define('AUSTRIA_WINS', 0);
define('AUSTRIA_DRAWS', 0);
define('AUSTRIA_BNS', 0);
define('SWITZERLAND_WINS', 0);
define('SWITZERLAND_DRAWS', 0);
define('SWITZERLAND_BNS', 0);

#TEAM 4
define('WALES_WINS', 0);
define('WALES_DRAWS', 0);
define('WALES_BNS', 0);
define('RUSSIA_WINS', 0);
define('RUSSIA_DRAWS', 0);
define('RUSSIA_BNS', 0);
define('ICELAND_WINS', 0);
define('ICELAND_DRAWS', 0);
define('ICELAND_BNS', 0);
define('POLAND_WINS', 0);
define('POLAND_DRAWS', 0);
define('POLAND_BNS', 0);

#TEAM 5
define('CZECH_WINS', 0);
define('CZECH_DRAWS', 0);
define('CZECH_BNS', 0);
define('SWEDEN_WINS', 0);
define('SWEDEN_DRAWS', 0);
define('SWEDEN_BNS', 0);
define('TURKEY_WINS', 0);
define('TURKEY_DRAWS', 0);
define('TURKEY_BNS', 0);
define('UKRAINE_WINS', 0);
define('UKRAINE_DRAWS', 0);
define('UKRAINE_BNS', 0);

#TEAM 6
define('REPUBLIC_WINS', 0);
define('REPUBLIC_DRAWS', 0);
define('REPUBLIC_BNS', 0);
define('ROMANIA_WINS', 0);
define('ROMANIA_DRAWS', 0);
define('ROMANIA_BNS', 0);
define('SLOVAKIA_WINS', 0);
define('SLOVAKIA_DRAWS', 0);
define('SLOVAKIA_BNS', 0);

#TEAM 7
define('HUNGARY_WINS', 0);
define('HUNGARY_DRAWS', 0);
define('HUNGARY_BNS', 0);
define('NORTHERN_WINS', 0);
define('NORTHERN_DRAWS', 0);
define('NORTHERN_BNS', 0);
define('ALBANIA_WINS', 0);
define('ALBANIA_DRAWS', 0);
define('ALBANIA_BNS', 0);

#PLAYER 1
define('MULLER_GOALS', 0);
define('MULLER_BNS', 0);
define('RONALDO_GOALS', 0);
define('RONALDO_BNS', 0);
define('GRIEZMANN_GOALS', 0);
define('GRIEZMANN_BNS', 0);

#PLAYER 2
define('GIROUD_GOALS', 0);
define('GIROUD_BNS', 0);
define('LEWANDOWSKI_GOALS', 0);
define('LEWANDOWSKI_BNS', 0);
define('KANE_GOALS', 0);
define('KANE_BNS', 0);

#PLAYER 3
define('LUKAKU_GOALS', 0);
define('LUKAKU_BNS', 0);
define('MARTIAL_GOALS', 0);
define('MARTIAL_BNS', 0);
define('MORATA_GOALS', 0);
define('MORATA_BNS', 0);
define('IBRAHIMOVIC_GOALS', 0);
define('IBRAHIMOVIC_BNS', 0);

#PLAYER 4
define('PELLE_GOALS', 0);
define('PELLE_BNS', 0);
define('GOTZE_GOALS', 0);
define('GOTZE_BNS', 0);
define('VARDY_GOALS', 0);
define('VARDY_BNS', 0);
define('ADURIZ_GOALS', 0);
define('ADURIZ_BNS', 0);

#PLAYER 5
define('HAZARD_GOALS', 0);
define('HAZARD_BNS', 0);
define('GIGNAC_GOALS', 0);
define('GIGNAC_BNS', 0);
define('STURRIDGE_GOALS', 0);
define('STURRIDGE_BNS', 0);
define('MANDZUKIC_GOALS', 0);
define('MANDZUKIC_BNS', 0);

#PLAYER 6
define('GOMEZ_GOALS', 0);
define('GOMEZ_BNS', 0);
define('ROONEY_GOALS', 0);
define('ROONEY_BNS', 0);
define('BRUYNE_GOALS', 0);
define('BRUYNE_BNS', 0);
define('BALE_GOALS', 0);
define('BALE_BNS', 0);

#PLAYER 7
define('ZAZA_GOALS', 0);
define('ZAZA_BNS', 0);
define('DZYUBA_GOALS', 0);
define('DZYUBA_BNS', 0);
define('SHAQIRI_GOALS', 0);
define('SHAQIRI_BNS', 0);
define('JANKO_GOALS', 0);
define('JANKO_BNS', 0);

#PLAYER 8
define('KOKORIN_GOALS', 0);
define('KOKORIN_BNS', 0);
define('YARMOLENKO_GOALS', 0);
define('YARMOLENKO_BNS', 0);
define('YILMAZ_GOALS', 0);
define('YILMAZ_BNS', 0);

#PLAYER 9
define('NECID_GOALS', 0);
define('NECID_BNS', 0);
define('HAMSIK_GOALS', 0);
define('HAMSIK_BNS', 0);
define('BJARNASON_GOALS', 0);
define('BJARNASON_BNS', 0);



define('FRANCE', serialize(array(FRANCE_WINS, FRANCE_DRAWS, FRANCE_BNS)));
define('GERMANY', serialize(array(GERMANY_WINS, GERMANY_DRAWS, GERMANY_BNS)));
define('SPAIN', serialize(array(SPAIN_WINS, SPAIN_DRAWS, SPAIN_BNS)));
define('ENGLAND', serialize(array(ENGLAND_WINS, ENGLAND_DRAWS, ENGLAND_BNS)));
define('BELGIUM', serialize(array(BELGIUM_WINS, BELGIUM_DRAWS, BELGIUM_BNS)));
define('ITALY', serialize(array(ITALY_WINS, ITALY_DRAWS, ITALY_BNS)));
define('PORTUGAL', serialize(array(PORTUGAL_WINS, PORTUGAL_DRAWS, PORTUGAL_BNS)));
define('CROATIA', serialize(array(CROATIA_WINS, CROATIA_DRAWS, CROATIA_BNS)));
define('AUSTRIA', serialize(array(AUSTRIA_WINS, AUSTRIA_DRAWS, AUSTRIA_BNS)));
define('SWITZERLAND', serialize(array(SWITZERLAND_WINS, SWITZERLAND_DRAWS, SWITZERLAND_BNS)));
define('WALES', serialize(array(WALES_WINS, WALES_DRAWS, WALES_BNS)));
define('ICELAND', serialize(array(ICELAND_WINS, ICELAND_DRAWS, ICELAND_BNS)));
define('RUSSIA', serialize(array(RUSSIA_WINS, RUSSIA_DRAWS, RUSSIA_BNS)));
define('POLAND', serialize(array(POLAND_WINS, POLAND_DRAWS, POLAND_BNS)));
define('CZECH', serialize(array(CZECH_WINS, CZECH_DRAWS, CZECH_BNS)));
define('SWEDEN', serialize(array(SWEDEN_WINS, SWEDEN_DRAWS, SWEDEN_BNS)));
define('TURKEY', serialize(array(TURKEY_WINS, TURKEY_DRAWS, TURKEY_BNS)));
define('UKRAINE', serialize(array(UKRAINE_WINS, UKRAINE_DRAWS, UKRAINE_BNS)));
define('REPUBLIC', serialize(array(REPUBLIC_WINS, REPUBLIC_DRAWS, REPUBLIC_BNS)));
define('ROMANIA', serialize(array(ROMANIA_WINS, ROMANIA_DRAWS, ROMANIA_BNS)));
define('SLOVAKIA', serialize(array(SLOVAKIA_WINS, SLOVAKIA_DRAWS, SLOVAKIA_BNS)));
define('HUNGARY', serialize(array(HUNGARY_WINS, HUNGARY_DRAWS, HUNGARY_BNS)));
define('NORTHERN', serialize(array(NORTHERN_WINS, NORTHERN_DRAWS, NORTHERN_BNS)));
define('ALBANIA', serialize(array(ALBANIA_WINS, ALBANIA_DRAWS, ALBANIA_BNS)));

define('MULLER', serialize(array(MULLER_GOALS, MULLER_BNS)));
define('RONALDO', serialize(array(RONALDO_GOALS, RONALDO_BNS)));
define('GRIEZMANN', serialize(array(GRIEZMANN_GOALS, GRIEZMANN_BNS)));
define('GIROUD', serialize(array(GIROUD_GOALS, GIROUD_BNS)));
define('LEWANDOWSKI', serialize(array(LEWANDOWSKI_GOALS, LEWANDOWSKI_BNS)));
define('KANE', serialize(array(KANE_GOALS, KANE_BNS)));
define('LUKAKU', serialize(array(LUKAKU_GOALS, LUKAKU_BNS)));
define('MARTIAL', serialize(array(MARTIAL_GOALS, MARTIAL_BNS)));
define('MORATA', serialize(array(MORATA_GOALS, MORATA_BNS)));
define('IBRAHIMOVIC', serialize(array(IBRAHIMOVIC_GOALS, IBRAHIMOVIC_BNS)));
define('PELLE', serialize(array(PELLE_GOALS, PELLE_BNS)));
define('GOTZE', serialize(array(GOTZE_GOALS, GOTZE_BNS)));
define('VARDY', serialize(array(VARDY_GOALS, VARDY_BNS)));
define('ADURIZ', serialize(array(ADURIZ_GOALS, ADURIZ_BNS)));
define('HAZARD', serialize(array(HAZARD_GOALS, HAZARD_BNS)));
define('GIGNAC', serialize(array(GIGNAC_GOALS, GIGNAC_BNS)));
define('STURRIDGE', serialize(array(STURRIDGE_GOALS, STURRIDGE_BNS)));
define('MANDZUKIC', serialize(array(MANDZUKIC_GOALS, MANDZUKIC_BNS)));
define('GOMEZ', serialize(array(GOMEZ_GOALS, GOMEZ_BNS)));
define('ROONEY', serialize(array(ROONEY_GOALS, ROONEY_BNS)));
define('BRUYNE', serialize(array(BRUYNE_GOALS, BRUYNE_BNS)));
define('BALE', serialize(array(BALE_GOALS, BALE_BNS)));
define('ZAZA', serialize(array(ZAZA_GOALS, ZAZA_BNS)));
define('DZYUBA', serialize(array(DZYUBA_GOALS, DZYUBA_BNS)));
define('SHAQIRI', serialize(array(SHAQIRI_GOALS, SHAQIRI_BNS)));
define('JANKO', serialize(array(JANKO_GOALS, JANKO_BNS)));
define('KOKORIN', serialize(array(KOKORIN_GOALS, KOKORIN_BNS)));
define('YARMOLENKO', serialize(array(YARMOLENKO_GOALS, YARMOLENKO_BNS)));
define('YILMAZ', serialize(array(YILMAZ_GOALS, YILMAZ_BNS)));
define('NECID', serialize(array(NECID_GOALS, NECID_BNS)));
define('HAMSIK', serialize(array(HAMSIK_GOALS, HAMSIK_BNS)));
define('BJARNASON', serialize(array(BJARNASON_GOALS, BJARNASON_BNS)));
